export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_ERROR = "USER_SIGN_ERROR";
export const CLEAR_USER_SIGN_ERROR = "CLEAR_USER_SIGN_ERROR";
export const GET_ALL_ARTICLES = "GET_ALL_ARTICLES";
export const UPLOAD_ARTICLES = "UPLOAD_ARTICLES";
export const SHOW_SUCCESS_MSG = "SHOW_SUCCESS_MSG";
